---
- hosts: kubernetes
  become: yes
  tasks:
    - name: Copy kubernetes YAML to remote server
      copy:
        src: kybernetes_deploy.yaml
        dest: /etc/yaml/kybernetes_deploy.yaml
        owner: ansadmin
        mode: 7777
    - name: run deployment and publish service
      command: kubectl apply -f /etc/yaml/kybernetes_deploy.yaml